# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 772151a086ad075a1deff9407c13bc1cb2db7ba1542c303f66caf6c1f484fb2ae599ece684e83eff569b70a1b7b95c14db8c9843216b9d869e07f33d38b64391

test:
  secret_key_base: 7f06ee2d5d223afdf6d60062343d4989408a44c79f54386cd13d0adac4861abcf8229dccf6a9fdf360c47dfed91c42ca5f1885751df1da555c6bdce12f11997e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
