# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ae4ead4d6f53ba5b97be4fda609f7b0ebbcaebde55c416d734c4009f267bcb27566b58ee5eb4707ba6fa569bfc16fb314dba15bd252434825c97979b244e174

test:
  secret_key_base: ca64bed4d88de4eb749a8889aaf30b8bef4ed555a8987fa1daa14d8d77990f5621dfac1e08254a9931956d8aff58ff2c3f8274292d6a48b7f949593749694ae8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
